language: python
install:
  - pip install tox 
  - pip install python-coveralls
script:
  - tox
env:
  - TOXENV: py34
after_success:
    coveralls -c ./humantrafficking_tips/.coveragerc -d ./humantrafficking_tips/.coverage
