# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTraffickingSMSTipsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('body', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('from_number', models.CharField(max_length=255)),
                ('to_number', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField()),
                ('tax_id', models.CharField(blank=True, max_length=255)),
                ('completed_enroll', models.BooleanField(default=False)),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('body', models.TextField(blank=True)),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('humantraffickingsmstipsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HumanTraffickingSMSTipsModel')),
                ('related_reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='sms.Reporter')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('sms.humantraffickingsmstipsmodel',),
        ),
        migrations.AddField(
            model_name='statement',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='sms.Tip'),
        ),
        migrations.AddField(
            model_name='photo',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sms.Tip'),
        ),
        migrations.AddField(
            model_name='location',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sms.Tip'),
        ),
    ]
