# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
