# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20161015_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
