# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
