# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HTRUBotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('investigation_id', models.CharField(blank=True, max_length=255)),
                ('analysts', models.ManyToManyField(related_name='cases_analyzed', to=settings.AUTH_USER_MODEL)),
                ('cases', models.ManyToManyField(related_name='_case_cases_+', to='sms.Case')),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('body', models.TextField(blank=True)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField()),
                ('tax_id', models.CharField(blank=True, max_length=255)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='SocialMediaHandle',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('service', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('body', models.TextField(blank=True)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('age', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('race', models.CharField(blank=True, max_length=255)),
                ('height', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255)),
                ('identifying_marks', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.AddField(
            model_name='case',
            name='descriptions',
            field=models.ManyToManyField(to='sms.Description'),
        ),
        migrations.AddField(
            model_name='case',
            name='photos',
            field=models.ManyToManyField(to='sms.Photo'),
        ),
        migrations.AddField(
            model_name='case',
            name='prosecutors',
            field=models.ManyToManyField(related_name='cases_prosecuted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='reporters',
            field=models.ManyToManyField(to='sms.Reporter'),
        ),
        migrations.AddField(
            model_name='case',
            name='statements',
            field=models.ManyToManyField(to='sms.Statement'),
        ),
        migrations.AddField(
            model_name='case',
            name='victims',
            field=models.ManyToManyField(to='sms.Victim'),
        ),
    ]
