# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('from_number', models.CharField(max_length=255)),
                ('to_number', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.AddField(
            model_name='case',
            name='locations',
            field=models.ManyToManyField(to='sms.Location'),
        ),
        migrations.AddField(
            model_name='case',
            name='messages',
            field=models.ManyToManyField(to='sms.Message'),
        ),
    ]
