# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20161008_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='completed_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
