# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0003_reporter_completed_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('htrubotmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.HTRUBotModel')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('sms.htrubotmodel',),
        ),
        migrations.RemoveField(
            model_name='case',
            name='analysts',
        ),
        migrations.RemoveField(
            model_name='case',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='case',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='case',
            name='htrubotmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='case',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='case',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='case',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='case',
            name='prosecutors',
        ),
        migrations.RemoveField(
            model_name='case',
            name='reporters',
        ),
        migrations.RemoveField(
            model_name='case',
            name='statements',
        ),
        migrations.RemoveField(
            model_name='case',
            name='victims',
        ),
        migrations.RemoveField(
            model_name='description',
            name='htrubotmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='socialmediahandle',
            name='htrubotmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='htrubotmodel_ptr',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='SocialMediaHandle',
        ),
        migrations.DeleteModel(
            name='Victim',
        ),
        migrations.AddField(
            model_name='location',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='sms.Tip'),
        ),
        migrations.AddField(
            model_name='photo',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sms.Tip'),
        ),
        migrations.AddField(
            model_name='statement',
            name='related_tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='sms.Tip'),
        ),
    ]
