# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20161008_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='related_reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='sms.Reporter'),
        ),
    ]
