# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_tip_related_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
