# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_location_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
